### ISSUE TITLE
Saturated (non-trapping) float to int conversions

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#21]
https://github.com/WebAssembly/nontrapping-float-to-int-conversions

**Comment by vshymanskyy** [comment]
Test script is now prepared to run tests for this proposal:
```sh
./run-spec-test.py ./proposals/nontrapping-float-to-int-conversions/*.json
```

**Comment by abalkin** [comment]
This may prove to be not as easy to implement as #22 because the proposal introduces 2-byte opcodes while AFAICT, wasm3 only supports 1-byte opcodes.

For future reference, the new instructions and their opcodes are as follows:


| Name | Opcode | Immediate | Description |
| ---- | ---- | ---- | ---- |
| `i32.trunc_sat_f32_s` | `0xfc` `0x00` | | :bowling: saturating form of `i32.trunc_f32_s` |
| `i32.trunc_sat_f32_u` | `0xfc` `0x01` | | :bowling: saturating form of `i32.trunc_f32_u` |
| `i32.trunc_sat_f64_s` | `0xfc` `0x02` | | :bowling: saturating form of `i32.trunc_f64_s` |
| `i32.trunc_sat_f64_u` | `0xfc` `0x03` | | :bowling: saturating form of `i32.trunc_f64_u` |
| `i64.trunc_sat_f32_s` | `0xfc` `0x04` | | :bowling: saturating form of `i64.trunc_f32_s` |
| `i64.trunc_sat_f32_u` | `0xfc` `0x05` | | :bowling: saturating form of `i64.trunc_f32_u` |
| `i64.trunc_sat_f64_s` | `0xfc` `0x06` | | :bowling: saturating form of `i64.trunc_f64_s` |
| `i64.trunc_sat_f64_u` | `0xfc` `0x07` | | :bowling: saturating form of `i64.trunc_f64_u` |

**Comment by vshymanskyy** [comment]
@abalkin you're right. I'll start with implementing the parsing part. This will later be a good example for SIMD and other extensions.

**Comment by abalkin** [comment]
@vshymanskyy - I think I now understand the compilation logic well enough to tackle the parsing part.  It looks like I will need to write a custom `M3Compiler` function to handle extended opcodes.  I can probably tackle this over the weekend unless you've started writing it already.

I also noticed that @MaxGraey has submitted #81 where he implemented the execution part.  I can reuse that code.

**Comment by abalkin** [comment]
Also, would it be ok to use C99 static array initialization syntax for `c_operations`?

In other words, instead of 

```c
    ...
    M3OP( "else",                0, none,   d_emptyOpList(),                    Compile_Nop ),          // 0x05

    M3OP_RESERVED, M3OP_RESERVED, M3OP_RESERVED, M3OP_RESERVED, M3OP_RESERVED,                          // 0x06 - 0x0a

    M3OP( "end",                 0, none,   d_emptyOpList(),                    Compile_End ),          // 0x0b
    ...
```

I would like to write

```c
    ...
    [0x05] = M3OP( "else",                0, none,   d_emptyOpList(),                    Compile_Nop ),
    [0x0b] = M3OP( "end",                 0, none,   d_emptyOpList(),                    Compile_End ),
    ...
```

otherwise, we would need over 50 `M3OP_RESERVED` placeholders to fill the gap between `0xc4` and `0xfc` opcodes.

**Comment by vshymanskyy** [comment]
@abalkin I started working on it, but then I realized it can require some performance testing/benchmarks. Anyway we can start with something, then improve later on..


> C99 static array initialization syntax

- Will most probably fail to compile on MSVC.

**Comment by vshymanskyy** [comment]
@abalkin no, it appears to be working on MSVC ;)
Let's o it this way - just use this syntax for the `0xfc` entry

**Comment by MaxGraey** [comment]
What about define more preserved macros:
```c
#define M3OP_RESERVED2  M3OP_RESERVED M3OP_RESERVED
#define M3OP_RESERVED4  M3OP_RESERVED2 M3OP_RESERVED2
#define M3OP_RESERVED8  M3OP_RESERVED4 M3OP_RESERVED4
#define M3OP_RESERVED16 M3OP_RESERVED8 M3OP_RESERVED8
#define M3OP_RESERVED32 M3OP_RESERVED16 M3OP_RESERVED16
...
etc
```

and later if we need skip `50` op codes just use something like:
```c
M3OP_RESERVED32 M3OP_RESERVED16 M3OP_RESERVED2
```

**Comment by vshymanskyy** [comment]
@MaxGraey Yup, could be done this way, but I think using this syntax for a single entry wont hurt.
We can fix when (and if) it causes any troubles.

**Comment by vshymanskyy** [comment]
@abalkin just wondering if you have had any progress on this, or should I continue working on it. Thanks ;)

**Comment by vshymanskyy** [comment]
Multi-byte opcodes are implemented, but the saturated float to int conversion operators only work on linux/gcc. So this still needs some improvements..

**Comment by MaxGraey** [comment]
I found how fix this for Clang but it only works with trunk =(
https://godbolt.org/z/-Jm923

**Comment by vshymanskyy** [comment]
@MaxGraey actually fixed this.
We have still a small (and unrelated) issue with Win32 x86 build, but `non-trapping float to int conversions` are good now. Thanks!
