### ISSUE TITLE
[WASI] implement preopening, add --dir flag

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#25]

**Comment by kanaka** [comment]
I would love to get the wasm implementation of mal (github.com/kanaka/mal) working with wasm3 (currently supports node, wasmtime, wasmer, lucet, etc). But the wasm3 hardcoded preopen file descriptors (https://github.com/wasm3/wasm3/blob/0ede79bb83077d6f7ff5057989ff4c2edab2e4cd/source/m3_api_wasi.c#L70) interfere with file I/O. 

Specifically, the mal tests fail because the test harness sets up a PTY for testing that means the file descriptors aren't in the expected layout. I can mangle them in the test harness, but that would be hacky and brittle. The right thing would be support for non-hardcoded pre-opens in wasm3 so +1 for this issue.

**Comment by vshymanskyy** [comment]
Will be replaced with #79

**Comment by vshymanskyy** [comment]
@kanaka hopefully switching WASI implementation will resolve this ;)
