### ISSUE TITLE
esp32-idf example fails when -DESP32 is defined

### ISSUE THREAD

**Issue by igrr** [wasm3/wasm3#28]
I've noticed that esp32-idf example doesn't define `-DESP32`, so `d_m3MaxFunctionStackHeight`  is not overridden in m3_config_platforms.h:

https://github.com/wasm3/wasm3/blob/066ad8d2ef0be6e0ffdc7982a22ff2c2fc807222/source/m3_config_platforms.h#L172-L173

Once I add `-DESP32`, the example stops working, and crashes with null pointer dereference at 
https://github.com/wasm3/wasm3/blob/066ad8d2ef0be6e0ffdc7982a22ff2c2fc807222/platforms/esp32-idf/main/main.cpp#L43

Not sure how to interpret this, as it was reported in https://github.com/wasm3/wasm3/issues/26#issuecomment-569766803 that esp32-pio example (which I assume defines -DESP32) works okay. I don't have a working PIO environment so can't verify that.

**Comment by vshymanskyy** [comment]
Thanks. will re-check that

**Comment by vshymanskyy** [comment]
@igrr there's one more, fundamental issue regarding ESP32 and ESP8266, that requires attention.
`wasm3` currently relies heavily on the tail call elimination in the host compiler.
Some time ago, I created this simplified (and self-contained) test:
https://github.com/wasm3/wasm3/blob/master/test/tailcall/ops.c
it can be compiled like this:
```sh
xtensa-lx106-elf-gcc -O3 -fverbose-asm -S ops.c -o esp8266.S
xtensa-esp32-elf-gcc -O3 -fverbose-asm -S ops.c -o esp32.S
```
Both compilers fail to perform tail call elimination, and I'm wondering if this is a platform limitation, or if there's something we can do about it.
For example Cortex-M0 and M1 also fail to perform this optimization (due to lack of some important instructions), M3 and M4 are OK.

I realize this is off-topic here but we can move this to a separate issue if needed

**Comment by igrr** [comment]
Tail calls seem to be not implemented for esp8266, not possible for esp32: https://github.com/pfalcon/ida-xtensa2/issues/1#issuecomment-261710552

**Comment by vshymanskyy** [comment]
AFAIK, there's no need to follow calling conventions for "internal"
functions (i.e. those that are not interfacing to other libraries)

**Comment by igrr** [comment]
That is correct, internal functions can use a non-standard calling convention. The only problem is that the Xtensa compiler doesn't allow changing the calling convention at function level or file level. The calling convention is chosen when the compiler itself is built. So when compiling C code, it will always follow the same calling convention.

That said, if there is a reasonably small number of functions which need the tail call optimization (some basic operations, as I understand), these can be implemented in assembly with tail call semantics.

**Comment by vshymanskyy** [comment]
Thank you for the clarification.
Yes these are all of the basic operations, but unfortunately it's quite a big set of functions.
I think that it may be possible to switch to [Labels as Values](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html) extension. This might work for more architectures/compilers.

**Comment by vshymanskyy** [comment]
Adding `-DESP32` didn't cause any issues on CI (maybe this was fixed with some recent changes):
https://github.com/wasm3/wasm3/runs/375648978#step:5:81
