### ISSUE TITLE
Unexpected behavior on the instruction `memory.grow`

### ISSUE THREAD

**Issue by erxiaozhou** [wasm3/wasm3#442]
## Description

### Current State
Output 1 and there is zero page in the memory.

### Expected State
Output 0xffffffff  and there is one page in the memory.

## Environment
- Code Version: git commit id 772f8f4648fcba75f77f894a6050db121e7651a2
- Hardware Architecture: x86\_64 
- Operating system: Ubuntu 20.04

## Steps to Reproduce

commands to build:
```
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
rm -rf build
mkdir build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .. 
ninja
```
[memory.grow_wasm3_sem.zip](https://github.com/wasm3/wasm3/files/12366448/memory.grow_wasm3_sem.zip)

```
build/wasm3 --func to_test <test_case>

**Comment by vshymanskyy** [comment]
The wasm file is valid, so it requires additional investigation

**Comment by tommie** [comment]
Minimal repro:

```wat
(module
  (func $to_test (result i32)
    i32.const -1
    memory.grow)
  (memory 1 5)
  (export "to_test" (func $to_test))
)
```

```console
$ ./build/wasm3 --func to_test test/regression/github-442.wasm 
Result: 1
$ wasmtime --invoke to_test test/regression/github-442.wasm 
warning: using `--invoke` with a function that returns values is experimental and may break in the future
-1
```

So this is a case of wasm3 interpreting "grow by -1 pages" as "grow by zero pages" instead of failing like wasmtime does.

The spec isn't super-clear on what growing by a negative number means:

https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-memory

The grow algorithm says "8. Append n times 64 KiB with value 0x00 to meminst.data", which is up for interpretation...

I guess it would make sense to disallow negative numbers, since they probably indicate a programming error.

The issue is that the -1 is interpreted as u32, and when added to 1 (the current size), it results in zero:

https://github.com/wasm3/wasm3/blob/256cd37bbd654c6b3dc1f7523ebc651ee4a87989/source/m3_exec.h#L716-L718

which `ResizeMemory` thinks is a fine size to resize to: https://github.com/wasm3/wasm3/blob/256cd37bbd654c6b3dc1f7523ebc651ee4a87989/source/m3_env.c#L371

It makes sense that `ResizeMemory` can shrink the memory, so this should be a sanity check in `op_MemGrow`.

**Comment by tommie** [comment]
(Resizing by zero is allowed in wasmtime.)
