### ISSUE TITLE
[WASI] Integrate uvwasi

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#79]
The idea is to replace the default custom WASI implementation with `uvwasi`: https://github.com/cjihrig/uvwasi
Maybe there are better options? Comments welcome.

**Comment by cjihrig** [comment]
If you move forward with this, feel free to ping me with any questions. FWIW, the majority of the Node.js integration with uvwasi can be found in these files:

- https://github.com/nodejs/node/blob/5b0308cd823a511098dadf9ddd5a35e3a9dbb424/src/node_wasi.cc
- https://github.com/nodejs/node/blob/5b0308cd823a511098dadf9ddd5a35e3a9dbb424/src/node_wasi.h

**Comment by prabirshrestha** [comment]
I'm working on [embedding wasm3 on vim](https://twitter.com/PrabirShrestha/status/1238928939545849856) and not sure if moving full to uvwasi is a great idea primiarily because vim may never and to bundle libuv. 

I would personally want both though the maintenance could be high.

**Comment by cjihrig** [comment]
Just a few observations about the libuv concern. Disclaimer: I'm not a maintainer of wasm3 and obviously a little biased 😄

- Looking at https://github.com/vim/vim/issues/4604, it doesn't seem like it's been decided that wasm support will definitely land, so this might be putting the cart before the horse a bit.
- Not wanting to take on libuv, or any library for that matter, as a dependency is a perfectly valid concern. That said, the WASI API requires a fair amount of cross platform C code for Windows alone, not to mention more exotic platforms like some of the IBM platforms. The size of the WASI API will likely continue to grow as well. libuv or not, you'll probably want something to abstract all of that away, and I'd rather go with something that is [battle tested](https://github.com/libuv/libuv/wiki/Projects-that-use-libuv). I know vim and neovim are different projects, but libuv seems to be working alright for neovim.
- I was under the impression that wasm3 allowed WASI to be disabled. I'm not that familiar with the internals though, so I could be wrong. If it can be disabled, would that address your concerns?
- I don't understand the comment about maintenance being high. libuv released version 1.0.0 in 2014, and has been backwards compatible ever since (minus two [accidental ABI breakages](https://abi-laboratory.pro/?view=timeline&l=libuv), but hey, bugs happen). We make a new release approximately once a month that would be a strictly drop in replacement for the old version. Releases could also be skipped if there is nothing interesting in them. In my opinion, targeting the WASI API itself (which is still unstable) would require more maintenance overhead at this point in time.

cc: @saghul in case you have anything to add.

**Comment by vshymanskyy** [comment]
WASI can be easily disabled.

**Comment by vshymanskyy** [comment]
uvwasi is integrated. Thanks @cjihrig !

You can select WASI implementation now:
```sh
cmake -DBUILD_WASI=uvwasi ..    # default
cmake -DBUILD_WASI=simple ..    # direct implementation (that was previously used)
cmake -DBUILD_WASI=metawasi ..  # used for emulating WASI in a WASI environment
```

**Comment by saghul** [comment]
Wooot! 🚀 🚀 🚀 🚀 🚀

**Comment by saghul** [comment]
Sorry I completely missed this @cjihrig . Ever since the current world situation has sstarted I've been swamped. Very happy to see this come along, can't wait to give it a shot on txiki.js!

**Comment by cjihrig** [comment]
No worries @saghul, I saw your talk on what the jitsi folks have been dealing with 😄 

Let me know if you run into issues integrating with txiki.js. I'm happy to try to work with you through it.

And thanks @vshymanskyy for all the help getting this landed.
