### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#8]
Bring `wasm3` to a level where it can run itself. JFF ;)

Actions list:
- [x] Improve interpreter so it can execute itself
- [x] Build in 32-bit mode (normal native x86 build) and fix spec tests
- [x] Build `wasm3.wasm`
- [x] Improve test script so we can run spec tests on `wasm3.wasm`
- [x] Fix spec tests for `wasm3.wasm`
- [x] Fix imported (native) function calls
- [x] Implement `MetaWASI` (redirect WASI calls to the host WASI environment)
- [ ] Run `WASI` apps in self-hosted mode
- [ ] Run spec tests in self-hosted mode

**Comment by vshymanskyy** [comment]
I've just got a proof-of-concept of "self-hosted" execution.
I.e. `wasm3` that runs `wasm3` that runs `fib(30)`
I was facing multiple issues, so I added a way to run spec tests on the `wasm3.wasm`. This also supports multiple host engines:
```sh
./run-spec-test.py --exec "wasirun ../build-wasi/wasm3.wasm"
# ./run-spec-test.py --exec "wasmer ../build-wasi/wasm3.wasm"
# ./run-spec-test.py --exec "wasmtime ../build-wasi/wasm3.wasm"
# ./run-spec-test.py --exec "iwasm ../build-wasi/wasm3.wasm"
```

**Comment by vshymanskyy** [comment]
There's also one more problem - imported `C/C++` functions are not called correctly in `wasm3.wasm`. This in turn prevents us from running `WASI` apps in `self-hosted` mode.

**Comment by vshymanskyy** [comment]
WASI build now passes spec tests (when runs under wasmer):
https://github.com/wasm3/wasm3/runs/368290246#step:7:89

**Comment by vshymanskyy** [comment]
`MetaWASI` is now [implemented](https://github.com/wasm3/wasm3/blob/master/source/m3_api_meta_wasi.c).
This allows self-hosted execution in WASI environment,
i.e. `Host WASI engine` -> `Wasm3` -> `Wasm3` -> `WASI app`

On `webassembly.sh`, you can now run:
```bash
wasm3 /tmp/wasm3.wasm /wasi-test.wasm
```

**Comment by ddotlic** [comment]
@vshymanskyy Sorry if this is considered as "hijacking" the item, but my question is very much related to all of the above...

I'm building an amusing demo of various technologies stacked on top of each other, most of it possible due to the existence of WASM.

This is how the runtime "stack" works: browser (Chrome) -> dotnet.wasm -> <some_dotnet_lib> -> <actual_wasm_to_run>.

The funny part is that while dotnet.wasm is normal wasm, the next link in the chain is regular .NET IL which is _interpreted_ by the previous link. Then that code "**compiles**" normal wasm (last link) into IL which is "executed JIT compiled" but is in fact interpreted by the previous link 🤪(the next-to-last link is none the wiser, it has no clue it's running in this kind of environment).

This is completely insane but works like a charm.

Now, I'm looking forward to making things slightly crazier and for that I "need" wasm3.

I'd like to insert wasm3 into the chain as the next-to-last link. The environment running the wasm3 in that scenario - the <some_dotnet_lib> itself is _not_ wasi (I am not even sure it will successfully run wasm3), but when you think about it having wasm3 execute some code boils down to passing the said code to wasm3 _somehow_ (not necessarily through wasi) - it's just bytes.

Is there a way to do this, maybe by using the wasm linear memory?

Thanks in advance for any pointer (pun intended). Cheers!

**Comment by vshymanskyy** [comment]
@ddotlic thanks for starting the discussion. wasm3 is not tightly connected to WASI (it can happily run without it).

Correct me if I'm wrong:
1. **some_dotnet_lib** translates **actual_wasm_to_run** into IL
2. **dotnet.wasm** interprets this IL

With wasm3, you'd expect:
1. **wasm3** interprets **actual_wasm_to_run**
2. **wasm3**  itself is translated to IL using with **some_dotnet_lib**
3. **dotnet.wasm** interprets this IL

**Comment by ddotlic** [comment]
@vshymanskyy Yes, exactly. The IL being interpreted is an implementation detail, **some_dotnet_lib** thinks it runs under normal JIT, but it doesn't 😄 

From the point of view of wasm3, you only need to know that you are being run under _some_ WASM (but not WASI) runtime, details are irrelevant. The question is: when I tell **some_dotnet_lib** to execute wasm and give it wasm3, is there an exported function I can call which will somehow know to execute yet-another-wasm bytecode?

**Comment by ddotlic** [comment]
@vshymanskyy IOW, the only question is: what can be run when using wasm build of wasm3 "on startup"? Since wasm3 itself is runtime, it would make sense to be able to call a function to trigger execution of the "actual" wasm and have some way of passing "actual" wasm to wasm3.

I may have given too much information before 😉 it really boils down to the above sentence.

**Comment by ddotlic** [comment]
@vshymanskyy OK, got it. So the out-of-box wasm build (that you IIUC publish to WAPM) cannot be used directly? What does the classic entry point do today?
I may have better luck adding an additional entry point maybe and then using the existing build process which produces wasm build?

**Comment by vshymanskyy** [comment]
This should work mostly - but at some moment you can get stuck with a specific `libc` function that relies on WASI API. I'd try building it with emscripten, this should be more straightforward.

**Comment by ddotlic** [comment]
@vshymanskyy OK, I don't have enough knowledge yet to ask better questions, will be checking out that Discord channel, thanks!

**Comment by vshymanskyy** [comment]
@ddotlic for example, take a look at https://github.com/wasm3/wasm3/blob/master/platforms/emscripten/main.c
You may need to eliminate some functionality, to bring the amount of `imported` functions to the minimum, so you don't need to implement them on the Host.

**Comment by ddotlic** [comment]
@vshymanskyy That appears to be an excellent starting point, thanks!

**Comment by vshymanskyy** [comment]
@ddotlic @loredanacirstea I added a new (`emscripten_lib`)[https://github.com/wasm3/wasm3/tree/master/platforms/emscripten_lib] platform, which should also answer some of your questions.
This demonstrates how to expose Wasm3 API to JS (using Emscripten).

**Comment by ddotlic** [comment]
@vshymanskyy Ah, I forgot to post my feedback...

Two relevant things:

1. I had issues with C related tooling on my macOS. This was very surprising and the only reason I even noticed something was wrong is because I accidentally used a Windows machine with WSL which is for all intents and purposes a Linux system; that worked fine yet the same scenario on macOS failed (issue was linking of some of the exported functions, I can't recall exactly)
2. I managed to recompile the project (on a macOS by eliminating a lot of stuff, yet nothing crucial, at least I hope 😉) such that it can be loaded and executed under a compliant WASM runtime. However, the runtime I've mentioned above failed running the wasm3, which may indicate that the runtime simply is not finished yet (or thoroughly tested) since it's just a hobby project of a single person; additionally, let's not forget the amount of (invisible) interpretation involved here, so any of the links in the chain could have failed 😃 

On top of that, the world suddenly changed 😞 and I had other things on my mind.

Still, I have not given up yet, so thanks for the reminder about this project and for the new target.

Stay safe!

**Comment by vshymanskyy** [comment]
This research is complete. YAAAY!
![image](https://user-images.githubusercontent.com/1506708/80348390-69287900-8876-11ea-8f50-3038658e14ad.png)
